[package]
name = "lemondoo/rope-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Shake = "sleitnick/shake@1.1.0"	
Trove = "sleitnick/trove@1.5.1"
Promise = "evaera/promise@4.0.0"
Cmdr = "evaera/cmdr@1.12.0"
Signal = "sleitnick/signal@2.0.3"